baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My blog'

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2

  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 3
[taxonomies]
  category = "categories"
  tag = "tags"
  author = "author"

